"use client";

import { FormEvent, useMemo, useState } from "react";

type Lang = "en" | "tr" | "pt";

const copy = {
  en: {
    nav: ["Services", "Investments", "How we work", "Contact"],
    eyebrow: "Portugal • Türkiye • Global",
    title: "Your trusted route to Portugal.",
    lead: "Immigration and investment guidance, coordinated from first assessment to final step by Portuguese and Turkish legal professionals.",
    cta: "Book a consultation", secondary: "Explore our services", trust: "Cross-border expertise. Local execution.",
    immigration: "Immigration services", immigrationLead: "Clear, case-specific support for the essential steps of living, working and building a future in Portugal.",
    investment: "Investment advisory", investmentLead: "Independent, opportunity-led guidance—from initial screening and due diligence to structuring and execution.",
    process: "A clear process, built around you", steps: [["01", "Understand", "We assess your goals, timeline, eligibility and risk profile."], ["02", "Design", "Our Portuguese and Turkish legal network shapes the right route and document plan."], ["03", "Deliver", "We coordinate applications, appointments, counterparties and follow-up."], ["04", "Stay close", "You receive practical updates and one point of contact throughout."]],
    legalTitle: "Two legal cultures. One coordinated team.", legalText: "Your matter is handled through close cooperation between Portuguese and Turkish lawyers and specialist partners. This gives you local legal insight in Portugal, clear communication in your language, and a coordinated view of cross-border implications.",
    contact: "Let’s discuss your route to Portugal", contactLead: "Tell us what you are planning. We will contact you to arrange an initial assessment.",
    fields: ["Full name", "Email", "Phone", "I am interested in", "Tell us briefly about your plans"], options: ["Immigration services", "Investment advisory", "Company formation", "Other"], send: "Send request", note: "Submitting opens a secure WhatsApp conversation with our team.", footer: "Immigration & investment guidance for Portugal.", disclaimer: "Information on this website is general and does not constitute legal, tax or investment advice. Services and eligibility depend on individual circumstances and current rules.",
    services: [
      ["NIF", "Portuguese tax number", "We support the preparation and submission of your Portuguese tax identification request—the number commonly needed for contracts, banking, tax matters and many everyday transactions."],
      ["NISS", "Social Security registration", "Guidance on the Social Security identification process for eligible foreign nationals, including document checks and coordination around employment, self-employment or company-related evidence."],
      ["Bank account opening", "Prepared for compliance", "We help organise the documents banks commonly request, select an appropriate banking route and coordinate the onboarding process. Final approval always remains with the bank."],
      ["Certification & notarisation", "Documents ready for use", "Coordination of certified copies, signature recognition, translations, apostilles and other formalities that may be required for Portuguese or cross-border procedures."],
      ["AIMA appointment assistance", "Support on the day that matters", "Preparation before your appointment, a final document review and in-person accompaniment where agreed—helping you understand the process and communicate confidently with the authorities."],
      ["D-type visas", "Long-stay routes", "Case assessment and application coordination for relevant Portuguese residence visa pathways, including work, entrepreneurship, highly qualified activity, study, family and income-based routes, subject to eligibility."],
      ["Global Talent Portugal", "Innovation and talent pathways", "Guidance for eligible founders, executives, investors and specialised talent seeking access to Portugal’s innovation ecosystem, with pathway assessment and coordination with relevant programme partners."],
      ["Company formation", "Build in Portugal", "End-to-end coordination of company setup—from structure and corporate documentation to registration, tax onboarding, banking preparation and introductions to accounting partners."],
    ],
    investments: [
      ["Fund investments", "Selection starts with suitability", "We help screen regulated fund opportunities, examine strategy, fees, liquidity, governance and risk disclosures, and coordinate legal and financial due diligence before any commitment."],
      ["Construction investment", "From feasibility to delivery", "Assessment of project fundamentals, licensing and contractor framework, budget and timeline risks, with coordinated technical and legal review throughout the investment lifecycle."],
      ["Land investment", "Potential begins below the surface", "Location, zoning, buildability, title, access and infrastructure are reviewed before purchase, followed by support with negotiation and transaction coordination."],
      ["Uber investment", "Mobility assets, commercially assessed", "Guidance on fleet or operator opportunities connected to ride-hailing, including operating structure, licensing context, vehicle economics, partner screening and scenario-based return analysis."],
      ["Company investment", "Invest with a full view", "Target search and commercial screening, valuation context, legal and financial due diligence, negotiation support and transaction coordination for direct investments in Portuguese businesses."],
    ]
  },
  tr: {
    nav: ["Hizmetler", "Yatırımlar", "Nasıl çalışıyoruz", "İletişim"], eyebrow: "Portekiz • Türkiye • Global", title: "Portekiz’e uzanan güvenilir yolunuz.", lead: "İlk değerlendirmeden son adıma kadar Portekizli ve Türk hukuk uzmanlarının koordinasyonuyla göçmenlik ve yatırım danışmanlığı.", cta: "Görüşme planlayın", secondary: "Hizmetleri inceleyin", trust: "Sınır ötesi uzmanlık. Yerel uygulama.", immigration: "Göçmenlik hizmetleri", immigrationLead: "Portekiz’de yaşamak, çalışmak ve gelecek kurmak için gerekli adımlarda açık, dosyanıza özel destek.", investment: "Yatırım danışmanlığı", investmentLead: "İlk fırsat analizinden hukuki ve finansal incelemeye, yapılandırmadan uygulamaya kadar bağımsız rehberlik.", process: "Size göre tasarlanmış açık bir süreç", steps: [["01", "Anlıyoruz", "Hedeflerinizi, takviminizi, uygunluğunuzu ve risk profilinizi değerlendiriyoruz."], ["02", "Tasarlıyoruz", "Portekizli ve Türk hukuk ağımız doğru yolu ve evrak planını oluşturuyor."], ["03", "Yürütüyoruz", "Başvuruları, randevuları, tarafları ve takip sürecini koordine ediyoruz."], ["04", "Yanınızda kalıyoruz", "Süreç boyunca düzenli bilgi ve tek iletişim noktası sunuyoruz."]], legalTitle: "İki hukuk kültürü. Tek koordineli ekip.", legalText: "İşlemleriniz Portekizli ve Türk avukatlar ile uzman çözüm ortaklarının yakın çalışmasıyla yürütülür. Böylece Portekiz’de yerel hukuk bilgisine, kendi dilinizde açık iletişime ve sınır ötesi etkileri gözeten bütüncül bir yaklaşıma ulaşırsınız.", contact: "Portekiz planınızı konuşalım", contactLead: "Ne planladığınızı bize anlatın. İlk değerlendirme görüşmesi için sizinle iletişime geçelim.", fields: ["Ad soyad", "E-posta", "Telefon", "İlgilendiğim alan", "Planınızdan kısaca bahsedin"], options: ["Göçmenlik hizmetleri", "Yatırım danışmanlığı", "Şirket kuruluşu", "Diğer"], send: "Talep gönder", note: "Form gönderildiğinde ekibimizle güvenli WhatsApp görüşmesi açılır.", footer: "Portekiz için göçmenlik ve yatırım danışmanlığı.", disclaimer: "Bu sitedeki bilgiler geneldir; hukuki, vergisel veya yatırım tavsiyesi değildir. Hizmetler ve uygunluk, kişisel koşullara ve güncel kurallara göre değişir.",
    services: [["NIF", "Portekiz vergi numarası", "Sözleşmeler, banka işlemleri, vergi süreçleri ve günlük pek çok işlem için gerekli olan Portekiz vergi kimlik numarası başvurusunda evrak hazırlığı ve başvuru desteği."], ["NISS", "Sosyal Güvenlik kaydı", "Çalışma, serbest meslek veya şirket bağlantılı kanıtlar dahil olmak üzere uygun yabancılar için Sosyal Güvenlik numarası sürecinde evrak kontrolü ve koordinasyon."], ["Banka hesabı açılışı", "Uyum sürecine hazır dosya", "Bankaların talep ettiği belgelerin hazırlanması, uygun bankacılık yolunun belirlenmesi ve müşteri kabul sürecinin koordinasyonu. Nihai karar bankaya aittir."], ["Belge tasdiki ve noter işlemleri", "Kullanıma hazır evraklar", "Portekiz’de veya sınır ötesi işlemlerde gerekli olabilecek onaylı suret, imza tasdiki, tercüme, apostil ve diğer resmî işlemlerin koordinasyonu."], ["AIMA randevusuna eşlik", "Önemli günde yanınızda", "Randevu öncesi hazırlık, son evrak kontrolü ve kararlaştırıldığı durumda yüz yüze eşlik; süreci anlamanıza ve kurumla güvenle iletişim kurmanıza destek."], ["D tipi vizeler", "Uzun süreli ikamet yolları", "Çalışma, girişimcilik, yüksek nitelikli faaliyet, eğitim, aile ve gelir temelli yollar dahil uygun Portekiz ikamet vizaları için dosya analizi ve başvuru koordinasyonu."], ["Global Talent Portugal", "İnovasyon ve yetenek yolları", "Portekiz’in inovasyon ekosistemine erişmek isteyen uygun kurucu, yönetici, yatırımcı ve uzmanlar için program uygunluk analizi ve ilgili paydaşlarla koordinasyon."], ["Şirket kurulumu", "Portekiz’de işinizi kurun", "Şirket yapısı ve kurumsal evraklardan tescil, vergi başlangıcı, banka hazırlığı ve muhasebe çözüm ortaklarına yönlendirmeye kadar uçtan uca koordinasyon."]],
    investments: [["Fon yatırımları", "Seçim uygunlukla başlar", "Düzenlemeye tabi fon fırsatlarının strateji, ücret, likidite, yönetişim ve risk açısından incelenmesi; karar öncesi hukuki ve finansal durum tespitinin koordinasyonu."], ["İnşaat yatırımı", "Fizibiliteden teslimata", "Proje temelleri, ruhsatlar, yüklenici yapısı, bütçe ve zaman risklerinin değerlendirilmesi; yatırım süresince teknik ve hukuki incelemenin koordinasyonu."], ["Arazi yatırımı", "Potansiyel detaylarda başlar", "Satın alma öncesi konum, imar, yapılaşma hakkı, tapu, erişim ve altyapı incelemesi; ardından müzakere ve işlem koordinasyonu."], ["Uber yatırımı", "Mobilite varlıklarına ticari bakış", "Araç filosu veya operatör fırsatlarında işletme yapısı, lisans çerçevesi, araç ekonomisi, iş ortağı kontrolü ve senaryo bazlı getiri analizi."], ["Şirket yatırımı", "Bütünü görerek yatırım", "Portekiz şirketlerine doğrudan yatırım için hedef arama, ticari değerlendirme, değerleme çerçevesi, hukuki-finansal inceleme, müzakere ve işlem koordinasyonu."]]
  },
  pt: {
    nav: ["Serviços", "Investimentos", "Como trabalhamos", "Contacto"], eyebrow: "Portugal • Turquia • Global", title: "O seu caminho de confiança para Portugal.", lead: "Consultoria de imigração e investimento, coordenada desde a primeira avaliação até à conclusão por profissionais jurídicos portugueses e turcos.", cta: "Marcar uma consulta", secondary: "Conhecer os serviços", trust: "Experiência internacional. Execução local.", immigration: "Serviços de imigração", immigrationLead: "Apoio claro e personalizado nos passos essenciais para viver, trabalhar e construir um futuro em Portugal.", investment: "Consultoria de investimento", investmentLead: "Orientação independente, da análise inicial e due diligence à estruturação e execução.", process: "Um processo claro, pensado para si", steps: [["01", "Compreender", "Avaliamos objetivos, calendário, elegibilidade e perfil de risco."], ["02", "Planear", "A nossa rede jurídica portuguesa e turca define a rota e o plano documental."], ["03", "Executar", "Coordenamos pedidos, marcações, intervenientes e acompanhamento."], ["04", "Acompanhar", "Recebe atualizações práticas e um único ponto de contacto."]], legalTitle: "Duas culturas jurídicas. Uma equipa coordenada.", legalText: "O seu processo é conduzido em estreita colaboração entre advogados portugueses e turcos e parceiros especializados. Beneficia de conhecimento jurídico local, comunicação clara no seu idioma e uma visão coordenada das implicações internacionais.", contact: "Vamos falar do seu projeto em Portugal", contactLead: "Conte-nos o que está a planear. Entraremos em contacto para marcar uma avaliação inicial.", fields: ["Nome completo", "E-mail", "Telefone", "Tenho interesse em", "Descreva brevemente os seus planos"], options: ["Serviços de imigração", "Consultoria de investimento", "Constituição de empresa", "Outro"], send: "Enviar pedido", note: "Ao enviar, abre uma conversa segura de WhatsApp com a nossa equipa.", footer: "Consultoria de imigração e investimento em Portugal.", disclaimer: "A informação deste site é geral e não constitui aconselhamento jurídico, fiscal ou de investimento. Os serviços e a elegibilidade dependem das circunstâncias individuais e das regras em vigor.",
    services: [["NIF", "Número fiscal português", "Apoiamos a preparação e apresentação do pedido do número de identificação fiscal, habitualmente necessário para contratos, banca, obrigações fiscais e muitas operações do dia a dia."], ["NISS", "Registo na Segurança Social", "Orientação no processo de obtenção do número de Segurança Social para cidadãos estrangeiros elegíveis, com revisão documental e coordenação de comprovativos profissionais ou empresariais."], ["Abertura de conta bancária", "Dossier preparado para compliance", "Organizamos a documentação habitualmente solicitada pelos bancos, identificamos a via adequada e coordenamos o onboarding. A aprovação final pertence sempre ao banco."], ["Certificação e atos notariais", "Documentos prontos a utilizar", "Coordenação de cópias certificadas, reconhecimento de assinaturas, traduções, apostilas e outras formalidades necessárias em processos portugueses ou internacionais."], ["Acompanhamento na AIMA", "Consigo no momento decisivo", "Preparação prévia, revisão final dos documentos e acompanhamento presencial quando acordado, para compreender o processo e comunicar com confiança junto das autoridades."], ["Vistos tipo D", "Vias de longa duração", "Avaliação e coordenação de pedidos para vias de residência relevantes, incluindo trabalho, empreendedorismo, atividade altamente qualificada, estudo, família e rendimentos, sujeitas a elegibilidade."], ["Global Talent Portugal", "Vias de inovação e talento", "Orientação para fundadores, executivos, investidores e talento especializado elegíveis, com avaliação da via e coordenação com os parceiros relevantes do ecossistema de inovação."], ["Constituição de empresa", "Criar em Portugal", "Coordenação integral, da estrutura societária e documentação ao registo, enquadramento fiscal, preparação bancária e ligação a parceiros de contabilidade."]],
    investments: [["Investimento em fundos", "A seleção começa pela adequação", "Análise de oportunidades em fundos regulados: estratégia, comissões, liquidez, governação e riscos, com coordenação da due diligence jurídica e financeira."], ["Investimento em construção", "Da viabilidade à entrega", "Avaliação dos fundamentos, licenciamento, empreitada, orçamento e calendário, com revisão técnica e jurídica coordenada ao longo do projeto."], ["Investimento em terrenos", "O potencial começa nos detalhes", "Análise prévia de localização, planeamento, capacidade construtiva, titularidade, acessos e infraestruturas, seguida de apoio na negociação e transação."], ["Investimento Uber", "Ativos de mobilidade com visão comercial", "Orientação em oportunidades de frota ou operador: estrutura, enquadramento de licenças, economia dos veículos, parceiros e cenários de retorno."], ["Investimento em empresas", "Investir com visão completa", "Pesquisa e análise de alvos, contexto de avaliação, due diligence jurídica e financeira, negociação e coordenação de investimentos diretos em empresas portuguesas."]]
  }
} as const;

function Arrow() { return <span aria-hidden="true">↗</span>; }

export default function Home() {
  const [lang, setLang] = useState<Lang>("en");
  const t = copy[lang];
  const [openService, setOpenService] = useState<number | null>(0);
  const [formStatus, setFormStatus] = useState<"idle" | "sending" | "success" | "error">("idle");
  const allServices = useMemo(() => t.services, [t]);

  async function submit(e: FormEvent<HTMLFormElement>) {
    e.preventDefault();
    const form = e.currentTarget;
    const data = Object.fromEntries(new FormData(form).entries());
    setFormStatus("sending");
    try {
      const response = await fetch("/api/contact", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(data),
      });
      if (!response.ok) throw new Error("Contact request failed");
      form.reset();
      setFormStatus("success");
    } catch {
      setFormStatus("error");
    }
  }

  return <main>
    <header className="nav-wrap">
      <a className="brand" href="#top" aria-label="Rema Consultant home"><span className="brand-mark">R</span><span>REMA<small>CONSULTANT</small></span></a>
      <nav>{t.nav.map((n, i) => <a key={n} href={["#services", "#investments", "#process", "#contact"][i]}>{n}</a>)}</nav>
      <div className="language" aria-label="Language selector">{(["en", "tr", "pt"] as Lang[]).map(l => <button className={lang === l ? "active" : ""} key={l} onClick={() => setLang(l)}>{l.toUpperCase()}</button>)}</div>
      <a className="nav-cta" href="#contact">{t.cta} <Arrow /></a>
    </header>

    <section id="top" className="hero">
      <div className="hero-shade" />
      <div className="hero-content"><p className="eyebrow">{t.eyebrow}</p><h1>{t.title}</h1><p className="hero-lead">{t.lead}</p><div className="hero-actions"><a className="button light" href="#contact">{t.cta} <Arrow /></a><a className="text-link" href="#services">{t.secondary} ↓</a></div></div>
      <div className="hero-note"><span>REMA / 01</span><p>{t.trust}</p></div>
    </section>

    <section id="services" className="section services"><div className="section-head"><p className="kicker">01 — RELOCATION</p><h2>{t.immigration}</h2><p>{t.immigrationLead}</p></div>
      <div className="service-layout"><div className="service-image"><div className="image-label">Lisbon, Portugal <span>38.72° N</span></div></div><div className="accordion">{allServices.map((s, i) => <article className={openService === i ? "open" : ""} key={s[0]}><button onClick={() => setOpenService(openService === i ? null : i)} aria-expanded={openService === i}><span className="service-num">{String(i + 1).padStart(2, "0")}</span><span><b>{s[0]}</b><small>{s[1]}</small></span><i>{openService === i ? "−" : "+"}</i></button>{openService === i && <p>{s[2]}</p>}</article>)}</div></div>
    </section>

    <section id="investments" className="section investments"><div className="section-head light-head"><p className="kicker">02 — CAPITAL</p><h2>{t.investment}</h2><p>{t.investmentLead}</p></div><div className="investment-grid">{t.investments.map((s, i) => <article key={s[0]} className={`investment-card card-${i}`}><div className="card-image"/><div className="card-copy"><span>0{i + 1}</span><h3>{s[0]}</h3><h4>{s[1]}</h4><p>{s[2]}</p></div></article>)}</div></section>

    <section id="process" className="section process"><div className="section-head"><p className="kicker">03 — APPROACH</p><h2>{t.process}</h2></div><div className="steps">{t.steps.map(s => <article key={s[0]}><span>{s[0]}</span><h3>{s[1]}</h3><p>{s[2]}</p></article>)}</div></section>

    <section className="legal"><div className="legal-photo"/><div className="legal-copy"><p className="kicker">PORTUGAL × TÜRKİYE</p><h2>{t.legalTitle}</h2><p>{t.legalText}</p><a href="#contact">{t.cta} <Arrow /></a></div></section>

    <section id="contact" className="contact section"><div className="contact-intro"><p className="kicker">04 — CONTACT</p><h2>{t.contact}</h2><p>{t.contactLead}</p><a href="tel:+905536407886">TR: +90 553 640 78 86</a><a href="tel:+351912820548">PT: +351 912 820 548</a><a className="contact-email" href="mailto:ola@remaconsultant.com">ola@remaconsultant.com</a></div><form onSubmit={submit}><div className="honeypot" aria-hidden="true"><label>Website<input name="website" tabIndex={-1} autoComplete="off" /></label></div><div className="two"><label>{t.fields[0]}<input required name="name" autoComplete="name" /></label><label>{t.fields[1]}<input required type="email" name="email" autoComplete="email" /></label></div><div className="two"><label>{t.fields[2]}<input required name="phone" autoComplete="tel" /></label><label>{t.fields[3]}<select name="interest">{t.options.map(o => <option key={o}>{o}</option>)}</select></label></div><label>{t.fields[4]}<textarea name="message" rows={4}/></label><button className="button dark" type="submit" disabled={formStatus === "sending"}>{formStatus === "sending" ? (lang === "tr" ? "Gönderiliyor…" : lang === "pt" ? "A enviar…" : "Sending…") : t.send} <Arrow /></button>{formStatus === "success" && <p className="form-message success" role="status">{lang === "tr" ? "Talebiniz gönderildi. En kısa sürede sizinle iletişime geçeceğiz." : lang === "pt" ? "O seu pedido foi enviado. Entraremos em contacto brevemente." : "Your request has been sent. We will contact you shortly."}</p>}{formStatus === "error" && <p className="form-message error" role="alert">{lang === "tr" ? "Talebiniz gönderilemedi. Lütfen tekrar deneyin veya bize e-posta gönderin." : lang === "pt" ? "Não foi possível enviar. Tente novamente ou envie-nos um e-mail." : "We could not send your request. Please try again or email us."}</p>}<small>{lang === "tr" ? "Bilgileriniz güvenli biçimde ekibimize iletilir." : lang === "pt" ? "Os seus dados são enviados de forma segura à nossa equipa." : "Your details are sent securely to our team."}</small></form></section>

    <footer><div className="brand footer-brand"><span className="brand-mark">R</span><span>REMA<small>CONSULTANT</small></span></div><p>{t.footer}</p><div className="footer-contact"><a href="tel:+905536407886">TR: +90 553 640 78 86</a><a href="tel:+351912820548">PT: +351 912 820 548</a><a href="mailto:ola@remaconsultant.com">ola@remaconsultant.com</a></div><div className="footer-bottom"><span>© 2026 Rema Consultant</span><span>{t.disclaimer}</span></div></footer>
  </main>;
}
